### ISSUE TITLE
Fix lag when starting after the first 3 notes

### ISSUE THREAD

**Issue by maxrchung** [maxrchung/S2VX#196]
As Aaron, I want to make my game not lag so that I can play the game.

Only seems to happen on Aaron's setup. When trying to start playing in editor after the first 3 notes, the game lags really bad.

**Comment by Xenocidel** [comment]
Issue should be reproducible on any computer since the lag goes up the more notes are prior to the time in which you start Playing. With this information I found the root cause of the performance issue in `RemoveNotesUpTo()` in Notes.cs
