### ISSUE TITLE
Calculating hold/slider note score based on time held down

### ISSUE THREAD

**Issue by maxrchung** [maxrchung/S2VX#237]
As a player, I want to get score when I hold down a hold note, so I can feel validated when it's not just the start and end of the hold note.

- **If you are NOT holding the note, get points based on milliseconds passed. Also if you hold it too early, you get punished too. And also for holding passed the end.**
- We want some point calculation done while note is being held down. One way is having ticks and calculating ticks of scores when you hold down through it. Another simpler way is just calculating score on every frame - every missed millisecond adds to score.
- May require reworking of how hold notes work - currently hold note disappears if you miss it or let go too early

**Comment by Xenocidel** [comment]
Implementation details: For every time UpdateNote gets called, I will check if you're holding and hovering the note. If true and you're in VisibleBefore or VisibleAfter, the score will increase. If false and you're in During, the score will increase.
![image](https://user-images.githubusercontent.com/12549910/102308963-99fc1200-3f1c-11eb-9c61-a80798fcd9ba.png)
