### ISSUE TITLE
Commands affect Notes properties instead of Note directly

### ISSUE THREAD

**Issue by maxrchung** [maxrchung/S2VX#264]
As a developer, I want to have more efficient code to apply commands so that only one property is updated by a command.

We have a few commands that are modifying a Note directly. It would be better separation if we modified a higher level property inside of Notes and then referred to this property in a Note's Update.

- Make sure to apply color to Slider path and Anchor path

**Comment by Xenocidel** [comment]
Commands to be included in this change:

- ApproachesColorCommand
- HoldApproachesColorCommand
- HoldNotesAlphaCommand
- HoldNotesColorCommand
- HoldNotesOutlineColorCommand
- HoldNotesOutlineThicknessCommand
- NotesAlphaCommand
- NotesColorCommand
- NotesOutlineColorCommand
- NotesOutlineThicknessCommand
