### ISSUE TITLE
Continue writing the story

### ISSUE THREAD

**Issue by maxrchung** [maxrchung/S2VX#305]
As a story writer, I want to continue writing the story so that the story can get done down the line.

0 - 1/3: Max
1/3 - 2/3: Aaron
2/3 - 3/3: Alex

**Comment by maxrchung** [comment]
[story 20210117_1714.s2ry.txt](https://github.com/maxrchung/S2VX/files/5827301/story.20210117_1714.s2ry.txt)

**Comment by Xenocidel** [comment]
[story.txt](https://github.com/maxrchung/S2VX/files/5827428/story.txt)

**Comment by Naranja-Sagged** [comment]
[story.txt](https://github.com/maxrchung/S2VX/files/5827994/story.txt)
