### ISSUE TITLE
Finish the story

### ISSUE THREAD

**Issue by maxrchung** [maxrchung/S2VX#306]
As a story writer, I want to finish writing the story so that the story can get done and we can finally be happy.

0 - 1/3: Max
1/3 - 2/3: Aaron
2/3 - 3/3: Alex

**Comment by Xenocidel** [comment]
[story.txt](https://github.com/maxrchung/S2VX/files/5840820/story.txt)

**Comment by Xenocidel** [comment]
oh @Naranja-Sagged I ended mine at -90 rotation. Maybe you can do a rotate at the first note of your section?

**Comment by maxrchung** [comment]
> oh @Naranja-Sagged I ended mine at -90 rotation. Maybe you can do a rotate at the first note of your section?

I think it should be your responsibility to reset it back to 0. That's how I did my section leading to yours.

**Comment by Xenocidel** [comment]
yeah actually I just missed adding one so it works out. never mind
[story.txt](https://github.com/maxrchung/S2VX/files/5840988/story.txt)

**Comment by maxrchung** [comment]
Note: Make sure to remove extra notes that are not in your section. Otherwise, when we merge, they'll show up out of sync in the final output.


[story (removed extra notes) 20210122_2236.txt](https://github.com/maxrchung/S2VX/files/5859799/story.removed.extra.notes.20210122_2236.txt)

**Comment by Naranja-Sagged** [comment]
[story.txt](https://github.com/maxrchung/S2VX/files/5864270/story.txt)

**Comment by maxrchung** [comment]
[conflicts.txt](https://github.com/maxrchung/S2VX/files/5864314/conflicts.txt)

**Comment by maxrchung** [comment]
I will clean this up since my section has improper duplicates

**Comment by maxrchung** [comment]
Updated my section

[max.story.txt](https://github.com/maxrchung/S2VX/files/5865057/max.story.txt)

**Comment by maxrchung** [comment]
[merged.s2ry.txt](https://github.com/maxrchung/S2VX/files/5865092/merged.s2ry.txt)
[conflicts.txt](https://github.com/maxrchung/S2VX/files/5865093/conflicts.txt)

**Comment by maxrchung** [comment]
Video uploaded: https://youtu.be/hOCD0Tz4Ak0
