### ISSUE TITLE
Write wiki page to describe major/minor/patch differences better

### ISSUE THREAD

**Issue by maxrchung** [maxrchung/S2VX#349]
As a developer, I want to know how we mark the difference between major, minor, and patch changes so that we can make releases.

**Comment by maxrchung** [comment]
I made a section for determing release version and provided some examples: https://github.com/maxrchung/S2VX/wiki/Development-and-Release#determining-release-version

**Comment by Naranja-Sagged** [comment]
⬆💹

**Comment by Xenocidel** [comment]
+1
