### ISSUE TITLE
Write wiki page to go over testing

### ISSUE THREAD

**Issue by maxrchung** [maxrchung/S2VX#354]
As a developer, I would like to have better documentation for testing so that we can have a consistent and robust test suite.

Random place to paste images:

![image](https://user-images.githubusercontent.com/3955187/106693057-879c6d00-658a-11eb-8075-e2a9ac73c512.png)
![image](https://user-images.githubusercontent.com/3955187/106693207-d5b17080-658a-11eb-806d-08791eb3af38.png)

![image](https://user-images.githubusercontent.com/3955187/106696168-02688680-6591-11eb-80e7-68f6857acf44.png)

**Comment by maxrchung** [comment]
Wiki page finished here: https://github.com/maxrchung/S2VX/wiki/Testing

**Comment by Xenocidel** [comment]
+1

**Comment by Naranja-Sagged** [comment]
👍🚀
