### ISSUE TITLE
Update release instructions to include manual closing

### ISSUE THREAD

**Issue by maxrchung** [maxrchung/S2VX#359]
As a developer, I want to update the release instructions to include the manual closing of issues so that we properly document odd tasks we're forced to do.

- Seems like this is a GitHub issue with default branches: https://stackoverflow.com/questions/14154054/closing-a-github-issue-while-on-a-different-branch

**Comment by maxrchung** [comment]
I approve of this message.

**Comment by Naranja-Sagged** [comment]
Approve.
