### ISSUE TITLE
Find song for new story

### ISSUE THREAD

**Issue by maxrchung** [maxrchung/S2VX#419]
As a player, I want a second map to play so that I can play more maps.

- Aaron choosing song
- 2 minutes or less

**Comment by Xenocidel** [comment]
100 BPM; first beat at 0:00:402 ms
[Porter_Robinson__Madeon_-_Shelter.zip](https://github.com/maxrchung/S2VX/files/6239583/Porter_Robinson__Madeon_-_Shelter.zip)

#422 spawned for fixing issues with the snapping logic for the timeline
