### ISSUE TITLE
Determine time splits for new story

### ISSUE THREAD

**Issue by maxrchung** [maxrchung/S2VX#429]
As a story writer, I need to know what section I'm working on so I can work on it.

- 1/3: Alex
- 2/3: Max
- 3/3: Aaron

**Comment by Xenocidel** [comment]
One potential split is:
- beginning to 38:802
- 38:802 to 1:17:202
- 1:17:202 to end
However this would mean that the second section would have 0 choruses and the third section would have 2.
Alternatively, we can do a 4-split:
- beginning to 38:802 (39 seconds)
- 38:802 to 58:002 (19 seconds)
- 58:002 to 1:35:802 or 1:36:402 (39 seconds)
- rest (20 seconds)

**Comment by maxrchung** [comment]
My preference is for option 1. I think its good to have 3 clearly separated sections.

**Comment by maxrchung** [comment]
We decided to do option 2
