### ISSUE TITLE
Finish new story - Shelter

### ISSUE THREAD

**Issue by maxrchung** [maxrchung/S2VX#430]
* Deadline for finishing all parts of the story - May 21
* Merge will happen over May 21-23
* We'll have a working session on May 21

As a story writer, I want to decide the themes for the new story so that we can agree to have a somewhat cohesive story.

#419 contains story files

Time separations:
- beginning to 38:802 (39 seconds) - Alex
- 38:802 to 58:002 (19 seconds) - Aaron
- 58:002 to 1:35:802 (39 seconds) - Max
- rest (20 seconds) - Aaron

Notes
* Shouldn't be too hard - 4 stars
* Aaron must be able to FC.
* Smooth easings
* Colors have good contrast
* Try and make playable map
* **Ez 2 read**

**Comment by maxrchung** [comment]
Think I'm pretty much done with my part 

[shelter 20210518_1230.s2ry.txt](https://github.com/maxrchung/S2VX/files/6506127/shelter.20210518_1230.s2ry.txt)

**Comment by Xenocidel** [comment]
[aaron_shelter.s2ry.txt](https://github.com/maxrchung/S2VX/files/6519413/aaron_shelter.s2ry.txt)

**Comment by Naranja-Sagged** [comment]
[alex_shelter.s2ry.txt](https://github.com/maxrchung/S2VX/files/6525691/alex_shelter.s2ry.txt)

**Comment by Xenocidel** [comment]
```
Merge was successful
Merged 3 stories into "output.s2ry"

Note conflict:
HoldNote from 47014.489795918365 to 47464.489795918365
Note at 47152

Note conflict:
Note at 57401.99546485261
Note at 57401.99546485261

Note conflict:
Note at 57701.99546485261
Note at 57701.99546485261

Note conflict:
HoldNote from 106602 to 107052
Note at 106751.99546485262

Note conflict:
HoldNote from 108401.9954648526 to 109451.9954648526
Note at 109001.99546485262

Note conflict:
HoldNote from 108401.9954648526 to 109451.9954648526
Note at 109151.9954648526

Command conflict:
TimingChange from 402 to 11600
TimingChange from 402 to 11600

Command conflict:
TimingChange from 402 to 11600
TimingChange from 402 to 11600

Command conflict:
BackgroundColor from 29201.995464852607 to 29801.995464852607
BackgroundColor from 29201.995464852607 to 29801.995464852607

Command conflict:
CameraScale from 48401.99546485261 to 58001.9954648526
CameraScale from 57401.99546485261 to 58001.9954648526

Command conflict:
CameraRotate from 53201.99546485261 to 58001.9954648526
CameraRotate from 57401.99546485261 to 58001.9954648526

Command conflict:
BackgroundColor from 53201.99546485261 to 58001.9954648526
BackgroundColor from 57401.99546485261 to 58001.9954648526
```
