### ISSUE TITLE
Finish story

### ISSUE THREAD

**Issue by Xenocidel** [maxrchung/S2VX#489]
As a player I want one more map so that I can have more songs to start playing S2VX

Time breakups:
* Aaron: 0:00:000 - 0:38:824
* Alex: 0:38:824 - 1:15:882
* Max: 1:15:882 - 1:53:162

**Comment by maxrchung** [comment]
I had time this weekend so I finished my portion of the story [max.s2ry.txt](https://github.com/maxrchung/S2VX/files/7358563/max.s2ry.txt)

**Comment by Naranja-Sagged** [comment]
[story (2).txt](https://github.com/maxrchung/S2VX/files/7450524/story.2.txt)
Finished
