### ISSUE TITLE
Dragging selected note when note is not visible on NotesTimeline

### ISSUE THREAD

**Issue by Naranja-Sagged** [maxrchung/S2VX#84]
Currently trying to drag a selected note when not visible in NotesTimeline causes error
![whatsGoingOn](https://user-images.githubusercontent.com/34083577/91015019-4fd2d780-e59f-11ea-8b94-e074e70be151.png)

**Comment by Xenocidel** [comment]
Wasn't this fixed by deselecting it if it's not visible on the timeline?
